# Generated by Django 5.0.6 on 2024-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(verbose_name='Сообщение')),
                ('meta', models.JSONField(verbose_name='Метаданные')),
                ('created', models.DateTimeField(verbose_name='Время создания')),
                ('channel', models.PositiveSmallIntegerField(choices=[(0, 'API (api/message/)')], default=0, verbose_name='Канал')),
                ('next_task', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Номер задачи')),
                ('task_completed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
        ),
    ]
