# Generated by Django 5.0.6 on 2024-05-26 18:10

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(verbose_name='Сообщение')),
                ('meta', models.JSONField(verbose_name='Метаданные')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('channel', models.PositiveSmallIntegerField(choices=[(0, 'API (api/message/)')], default=0, verbose_name='Канал')),
                ('chain', models.JSONField(default=dict, verbose_name='Цепочка задач')),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['message', 'meta', 'chain'], name='JSONGinIndex')],
            },
        ),
    ]
