# Generated by Django 5.0.7 on 2024-07-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputqueue',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
