# Generated by Django 5.0.6 on 2024-05-13 17:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_queue', '0002_alter_inputqueue_created'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inputqueue',
            index=django.contrib.postgres.indexes.GinIndex(fields=['message', 'meta'], name='JSONGinIndex'),
        ),
    ]
