# Generated by Django 5.0.6 on 2024-05-21 09:25

import json.decoder
import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_queue', '0003_inputqueue_jsonginindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputqueue',
            name='message',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, verbose_name='Сообщение'),
        ),
    ]
