# Generated by Django 5.0.6 on 2024-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_queue', '0004_alter_inputqueue_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputqueue',
            name='message',
            field=models.JSONField(verbose_name='Сообщение'),
        ),
    ]
