# Generated by Django 5.0.6 on 2024-05-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_queue', '0006_remove_inputqueue_jsonginindex_inputqueue_chain_and_more'),
        ('organizations', '0005_alter_organization_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputqueue',
            name='next_task',
        ),
        migrations.RemoveField(
            model_name='inputqueue',
            name='task_completed',
        ),
        migrations.AddField(
            model_name='inputqueue',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='organizations.organization', verbose_name='Организация'),
        ),
    ]
