# Generated by Django 5.0.6 on 2024-05-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=200, verbose_name='Органицация')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Активна'), (1, 'Заблокирована'), (2, 'Заблокирована частично'), (3, 'В архиве')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Фактический адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Статус верефикации электронной почты')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='organizations.organization', verbose_name='Идентификатор организации')),
            ],
            options={
                'verbose_name': 'Реквизиты организации',
                'verbose_name_plural': 'Реквизиты рганизаций',
            },
        ),
    ]
