# Generated by Django 5.0.4 on 2024-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(None, '(Unknown)'), (0, 'Активна'), (1, 'Заблокирована'), (2, 'Заблокирована частично'), (3, 'В архиве')], default=0, verbose_name='Статус'),
        ),
    ]
