# Generated by Django 5.0.6 on 2024-05-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Активна'), (1, 'Заблокирована'), (2, 'Заблокирована частично'), (3, 'В архиве')], default=0, verbose_name='Статус'),
        ),
    ]
