upstream web-app {
    # Список бэкэнд серверов для проксирования
    server web-app:8000;
}


server {
    listen 80;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Параметры проксирования
    location / {
        # Если будет открыта корневая страница
        # все запросу пойдут к одному из серверов
        # в upstream web_app
        proxy_pass http://web-app;

        # Устанавливаем заголовки
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        # Отключаем перенаправление
        proxy_redirect off;
    }

    # подключаем статические файлы
    location /static/ {
        alias /web_app/static/;
    }
}


server {
    listen 8080;
    server_name flower;

    location / {
        proxy_pass http://flower:5555;
    }
}

