# Generated by Django 5.0.6 on 2024-05-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('blocked', models.BooleanField(default=False, verbose_name='Временная блокировка ключа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization', verbose_name='Идентификатор организации')),
            ],
            options={
                'verbose_name': 'API ключи организации',
                'verbose_name_plural': 'API ключи организаций',
                'db_table': 'api_api_keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='organizationapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked', False)), fields=('organization', 'name'), name='unique_organization_APY_Key_name_when_not_revoked', violation_error_message='Имя ключа должно быть уникальным'),
        ),
    ]
