# Generated by Django 5.0.4 on 2024-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('organizations', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationapikey',
            name='unique_organization_APY_Key_name_when_not_revoked',
        ),
        migrations.AddConstraint(
            model_name='organizationapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked', False)), fields=('organization', 'name'), name='unique_organization_APY_Key_name_when_not_revoked', violation_error_message='Имя ключа должно быть уникальным'),
        ),
    ]
